version: '3'
services:
# setup kafka and start streaming features
  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: kafka-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - kafka-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - kafka-zookeeper
      - broker
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=kafka-zookeeper:2181

  redis:
    image: redis
    container_name: feast-redis
    ports:
      - "6379:6379"

  feast-redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8081:8081"

  feast-kafka-titanic-consumer:
    container_name: feast-kafka-titanic-consumer
    build:
      context: feast_titanic_consumer
      dockerfile: Dockerfile
    depends_on:
      - broker
      - redis
      - kafka-titanic-producer
    restart: on-failure
    environment:
      - KAFKA_SERVER=broker:29092
      - TOPIC=passengers

  kafka-titanic-producer:
    container_name: kafka-titanic-producer
    build:
      context: kafka_titanic_producer
      dockerfile: Dockerfile
    depends_on:
      - broker
    restart: on-failure
    environment:
      - KAFKA_SERVER=broker:29092
      - TOPIC=passengers
