version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  push_server:
    container_name: feast_push_server
    build:
      context: .
      dockerfile: feature_repo/Dockerfile
    ports:
      - "6567:6566"
    volumes:
      - type: bind
        source: ./feature_repo/data/local_registry.db
        target: /data/local_registry.db
    links:
      - redis

  feature_server:
    container_name: feast_feature_server
    build:
      context: .
      dockerfile: feature_repo/Dockerfile
    ports:
      - "6566:6566"
    volumes:
      - type: bind
        source: ./feature_repo/data/local_registry.db
        target: /data/local_registry.db
    links:
      - redis