version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  push_server:
    container_name: feast_push_server
    build:
      context: .
      dockerfile: data_science_repo/feast_feature_store/Dockerfile
    ports:
      - "6567:6566"
    volumes:
      - type: bind
        source: ./feast_feature_store/data/registry.db
        target: /data/registry.db
    links:
      - redis

  feature_server:
    container_name: feast_feature_server
    build:
      context: .
      dockerfile: data_science_repo/feast_feature_store/Dockerfile
    ports:
      - "6566:6566"
    volumes:
      - type: bind
        source: ./feast_feature_store/data/registry.db
        target: /data/registry.db
    links:
      - redis